added: elements aligned to right and to center
8ctopus/sciter-layout pull request #2
Opened 2021-05-12 06:23 UTC by Barbarararara

Created align-01 and align-02 tabs with examples of child elements aligned to right and centered

2021-05-12 06:40 UTC, 8ctopus requested changes

2021-05-12 06:40 UTC, 8ctopus commented on align-01.html
> +    flow: horizontal;
the idea was not to use flow for align-01 and align-02. can you try to do it without flow?

2021-05-12 06:40 UTC, 8ctopus commented on align-02.html
> +    flow: horizontal;
same here

2021-05-13 04:22 UTC, Barbarararara commented
Deleted flow: horizontal on parent div

2021-05-13 05:46 UTC, 8ctopus approved these changes

2021-05-13 05:47 UTC, merged